// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Experience struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Year        *ExperienceYear  `json:"year"`
	Links       *ExperienceLinks `json:"links"`
}

type ExperienceYear struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type NewPost struct {
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}
